# Generated by Django 4.0.2 on 2022-09-04 11:22

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking_Detail',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apps.basemodel')),
                ('Event_Id', models.CharField(max_length=80)),
                ('Event_Name', models.CharField(max_length=100)),
                ('Total_amount', models.CharField(max_length=80)),
                ('Order_id', models.CharField(max_length=20)),
            ],
            bases=('apps.basemodel',),
        ),
        migrations.CreateModel(
            name='Event_detail',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apps.basemodel')),
                ('Event_img', models.ImageField(upload_to='images/')),
                ('Event_Name', models.CharField(default='', max_length=100)),
                ('Is_Carousel', models.CharField(default='', max_length=10)),
                ('Organizer', models.CharField(default='', max_length=200)),
                ('Category', models.CharField(default='', max_length=100)),
                ('Startdate', models.CharField(default='', max_length=10)),
                ('Starttime', models.CharField(default='', max_length=10)),
                ('Endtime', models.CharField(default='', max_length=10)),
                ('orgtype', models.CharField(default='', max_length=10)),
                ('Age', models.CharField(default='18+', max_length=4)),
                ('Language', models.CharField(default='Hinglish', max_length=50)),
                ('City', models.CharField(default='', max_length=100)),
                ('Fulladdress', models.CharField(default='', max_length=500)),
                ('Description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('TnC', ckeditor.fields.RichTextField(blank=True, default='', max_length=3500, null=True)),
                ('Status', models.CharField(default='Unpublished', max_length=800, null=True)),
            ],
            bases=('apps.basemodel',),
        ),
        migrations.CreateModel(
            name='Event_Ticket',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apps.basemodel')),
                ('Ticket_type', models.CharField(default='', max_length=150)),
                ('Description', models.TextField(default='', max_length=150)),
                ('Created_by', models.CharField(default='', max_length=200)),
                ('Price', models.CharField(default='', max_length=10)),
                ('Expected_Quantity', models.CharField(default='', max_length=10)),
                ('Expiry_Date', models.CharField(default='', max_length=10)),
                ('Expiry_Time', models.CharField(default='', max_length=10)),
                ('Additional_data', models.CharField(blank=True, default='', max_length=150, null=True)),
            ],
            bases=('apps.basemodel',),
        ),
        migrations.CreateModel(
            name='AllUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_customer', models.BooleanField(default=False)),
                ('is_organizer', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ordered_Tickets_Detail',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apps.basemodel')),
                ('TicketName', models.CharField(max_length=80)),
                ('Total_Ticket', models.CharField(max_length=100)),
                ('Total_Ticket_Price', models.CharField(max_length=80)),
                ('Booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.booking_detail')),
            ],
            bases=('apps.basemodel',),
        ),
        migrations.CreateModel(
            name='Customer_Data',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apps.basemodel')),
                ('Name', models.CharField(max_length=50)),
                ('Mobile', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('apps.basemodel',),
        ),
        migrations.CreateModel(
            name='Business_Data',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apps.basemodel')),
                ('Business_Name', models.CharField(max_length=50)),
                ('Contact', models.CharField(max_length=40)),
                ('Registered_As', models.CharField(default='', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('apps.basemodel',),
        ),
        migrations.AddField(
            model_name='booking_detail',
            name='Booked_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
