# Generated by Django 4.0.2 on 2022-10-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_booking_detail_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_detail',
            name='Spot_id',
            field=models.CharField(default='SPOT_ID', max_length=20),
        ),
        migrations.AddField(
            model_name='booking_detail',
            name='Tx_id_PG',
            field=models.CharField(default='CASHFREE_REF_ID', max_length=20),
        ),
    ]
